const DEFAULTS = { controller: "", secret: "", timeout: 3000, overlayEnabled: true, overlaySide: "right" };
const tabSiteDelays = new Map();
async function config() { return { ...DEFAULTS, ...(await chrome.storage.local.get(DEFAULTS)) }; }
function baseUrl(value) { const url = new URL(value.trim()); if (!["http:", "https:"].includes(url.protocol)) throw new Error("控制器地址必须使用 HTTP 或 HTTPS"); return url.origin + url.pathname.replace(/\/$/, ""); }
async function request(path) { const cfg = await config(); if (!cfg.controller) throw new Error("尚未配置 OpenClash/Mihomo 控制器地址"); const headers = { Accept: "application/json" }; if (cfg.secret) headers.Authorization = `Bearer ${cfg.secret}`; const response = await fetch(`${baseUrl(cfg.controller)}${path}`, { headers, signal: AbortSignal.timeout(Number(cfg.timeout) || 3000) }); if (!response.ok) throw new Error(`控制器返回 HTTP ${response.status}`); return response.json(); }
function hostOf(c) { const m = c.metadata || {}; return String(m.host || m.destination || c.host || m.remoteDestination || "").toLowerCase().replace(/\.$/, ""); }
function matches(host, target) { return Boolean(host) && (host === target || host.endsWith(`.${target}`) || target.endsWith(`.${host}`)); }
const countries = [["香港","🇭🇰","hk"],["hong kong","🇭🇰","hk"],["台湾","🇹🇼","tw"],["台灣","🇹🇼","tw"],["臺灣","🇹🇼","tw"],["taiwan","🇹🇼","tw"],["taipei","🇹🇼","tw"],["台北","🇹🇼","tw"],["臺北","🇹🇼","tw"],["日本","🇯🇵","jp"],["japan","🇯🇵","jp"],["东京","🇯🇵","jp"],["東京","🇯🇵","jp"],["新加坡","🇸🇬","sg"],["singapore","🇸🇬","sg"],["美国","🇺🇸","us"],["美國","🇺🇸","us"],["united states","🇺🇸","us"],["usa","🇺🇸","us"],["洛杉矶","🇺🇸","us"],["洛杉磯","🇺🇸","us"],["纽约","🇺🇸","us"],["紐約","🇺🇸","us"],["英国","🇬🇧","gb"],["英國","🇬🇧","gb"],["united kingdom","🇬🇧","gb"],["uk","🇬🇧","gb"],["德国","🇩🇪","de"],["德國","🇩🇪","de"],["germany","🇩🇪","de"],["法国","🇫🇷","fr"],["法國","🇫🇷","fr"],["france","🇫🇷","fr"],["韩国","🇰🇷","kr"],["韓國","🇰🇷","kr"],["korea","🇰🇷","kr"],["加拿大","🇨🇦","ca"],["澳大利亚","🇦🇺","au"],["澳洲","🇦🇺","au"],["荷兰","🇳🇱","nl"],["荷蘭","🇳🇱","nl"],["土耳其","🇹🇷","tr"],["印度","🇮🇳","in"],["俄罗斯","🇷🇺","ru"],["俄羅斯","🇷🇺","ru"],["瑞士","🇨🇭","ch"],["巴西","🇧🇷","br"]];
function countryFor(node) { const s = String(node || "").toLowerCase(); const emoji = s.match(/[\u{1F1E6}-\u{1F1FF}]{2}/u); const hit = countries.find(([key]) => s.includes(key)); const aliases = new Set(countries.map(([, , code]) => code)); const codeHit = s.match(/(?:^|[\s_\-[\]()])([a-z]{2})(?:$|[\s_\-[\]()])/i); const possible = codeHit?.[1]?.toLowerCase(); const code=hit?.[2] || (aliases.has(possible) ? possible : ""); const emojiByCode = code ? String.fromCodePoint(0x1f1e6 + code.charCodeAt(0)-97, 0x1f1e6 + code.charCodeAt(1)-97) : "🌐"; return { emoji: emoji?.[0] || hit?.[1] || emojiByCode, code, source: hit || (code && codeHit) ? "node-name" : "unknown" }; }
function nodeFromChains(chains) { const list = Array.isArray(chains) ? chains : []; for (const item of list) { const result = countryFor(item); if (result.code) return { name: item, country: result }; } const name = list.at(-1) || "DIRECT"; return { name, country: countryFor(name) }; }
const countryNames = { hk:"Hong Kong", tw:"Taiwan", jp:"Japan", sg:"Singapore", us:"United States", gb:"United Kingdom", de:"Germany", fr:"France", kr:"South Korea", ca:"Canada", au:"Australia", nl:"Netherlands", tr:"Türkiye", in:"India", ru:"Russia", ch:"Switzerland", br:"Brazil" };
function fullCountry(code, fallback="") { return countryNames[String(code||"").toLowerCase()] || fallback || ""; }
function ipFrom(value) { const s=String(value||""); return s.match(/(?<![\w:])(?:\d{1,3}\.){3}\d{1,3}(?![\w])/)?.[0] || s.match(/(?<![\w:])(?:[0-9a-f]{1,4}:){2,7}[0-9a-f]{1,4}(?![\w])/i)?.[0] || ""; }
function candidateIps(connection, proxy) { const values=[connection?.metadata?.remoteIP,connection?.metadata?.remoteAddress,connection?.metadata?.serverIP,connection?.metadata?.destinationIP,connection?.metadata?.sourceIP,connection?.remoteIP,proxy?.server,proxy?.address,proxy?.servername]; return [...new Set(values.map(ipFrom).filter(Boolean))]; }
async function geo(ip) { try { const r=await fetch(`https://ipwho.is/${encodeURIComponent(ip)}`,{signal:AbortSignal.timeout(3500)}); if(!r.ok)return null; const d=await r.json(); if(d.success===false||!d.country_code)return null; return {ip,country:d.country||"",code:String(d.country_code).toLowerCase()}; } catch (_) { return null; } }
async function resolveSiteIps(host) { if (!host || /^\d{1,3}(?:\.\d{1,3}){3}$/.test(host)) return ipFrom(host) ? [ipFrom(host)] : []; try { const r=await fetch(`https://dns.google/resolve?name=${encodeURIComponent(host)}&type=A`,{signal:AbortSignal.timeout(3500)}); const d=await r.json(); return (d.Answer||[]).map(x=>ipFrom(x.data)).filter(Boolean); } catch (_) { return []; } }
async function flagDataUrl(code) { if(!code)return ""; try { const r=await fetch(`https://flagcdn.com/w80/${code.toLowerCase()}.png`,{signal:AbortSignal.timeout(3500)}); if(!r.ok)return ""; const bytes=new Uint8Array(await r.arrayBuffer()); let binary=""; for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000)); return `data:image/png;base64,${btoa(binary)}`; } catch (_) { return ""; } }
async function inspect(target) { const data=await request("/connections"), connections=Array.isArray(data.connections)?data.connections:[], found=connections.filter(c=>matches(hostOf(c),target)).sort((a,b)=>String(b.start||"").localeCompare(String(a.start||""))); if(!found.length){let geoResult=null;for(const ip of await resolveSiteIps(target)){geoResult=await geo(ip);if(geoResult)break;}return{target,found:false,activeConnections:connections.length,node:"DIRECT",chainLabel:"直连",country:fullCountry(geoResult?.code,geoResult?.country),countryCode:(geoResult?.code||"").toUpperCase(),countrySource:geoResult?"site-ip":"unknown",proxyIp:geoResult?.ip||""};} const c=found[0],chains=Array.isArray(c.chains)?c.chains:[],selected=nodeFromChains(chains),node=selected.name,direct=node==="DIRECT"||node==="REJECT"; let delay=null,proxy=null,geoResult=null,named=selected.country,source=named.code?"node-name":"unknown"; if(!direct){try{delay=(await request(`/proxies/${encodeURIComponent(node)}/delay?url=${encodeURIComponent("https://www.gstatic.com/generate_204")}&timeout=5000`)).delay??null;}catch(_){} if(!named.code){try{proxy=await request(`/proxies/${encodeURIComponent(node)}`);}catch(_){} for(const ip of candidateIps(c,proxy)){geoResult=await geo(ip);if(geoResult)break;} source=geoResult?"api-ip":"unknown";}} else {for(const ip of candidateIps(c,null)){geoResult=await geo(ip);if(geoResult)break;}if(!geoResult){for(const ip of await resolveSiteIps(target)){geoResult=await geo(ip);if(geoResult)break;}}source=geoResult?"site-ip":"unknown";} const code=(named.code||geoResult?.code||"").toUpperCase(),country=named.code?fullCountry(named.code):fullCountry(geoResult?.code,geoResult?.country);return{target,found:true,activeConnections:connections.length,host:hostOf(c),rule:c.rule||"未知",rulePayload:c.rulePayload||"",chains,node:direct?"DIRECT":node,chainLabel:direct?"直连":chains.join(" → "),country,countryCode:code,countrySource:direct?source:(named.code?"node-name":source),proxyIp:geoResult?.ip||"",delay,type:c.metadata?.type||c.type||"",network:c.metadata?.network||"",start:c.start||"",closed:c.closed??false}; }
// Chrome 的 action.setIcon 对动态 ImageData/远程图片在部分版本中会报 Icon invalid。
// 保留本地 PNG 作为稳定插件图标；落地国旗在弹窗和网页浮窗中使用 PNG。
async function updateBadge(result, tabId) { const direct=!result?.found||result.node==="DIRECT"; const text=direct?"直":(result.countryCode||"🌐"); const scope=tabId?{tabId}:{}; await chrome.action.setBadgeText({text,...scope}); await chrome.action.setBadgeBackgroundColor({color:direct?"#6b7280":"#356ae6",...scope}); await chrome.action.setTitle({title:direct?"代理链助手：直连":`代理链助手：${result.country||"未知归属地"} ${result.chainLabel||result.node}`,...scope}); if(tabId) await chrome.tabs.sendMessage(tabId,{type:"overlayResult",data:result}).catch(()=>{}); }
chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{(async()=>{if(message.type==="test")return{version:await request("/version"),proxies:Object.keys((await request("/proxies")).proxies||{}).length};if(message.type==="inspect"){const tabId=_sender.tab?.id;if(tabId&&Number.isFinite(message.siteDelay))tabSiteDelays.set(tabId,message.siteDelay);const r=await inspect(message.target);r.siteDelay=Number.isFinite(message.siteDelay)?message.siteDelay:(tabId?tabSiteDelays.get(tabId)??null:null);r.flagDataUrl=await flagDataUrl(r.countryCode);await updateBadge(r,tabId);return r;}if(message.type==="overlayConfig")return config();throw new Error("未知请求");})().then(sendResponse).catch(e=>sendResponse({error:e.message||String(e)}));return true;});
